default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # Prepares the Fastlane environment for use in CI systems
    setup_ci(
      provider: "circleci"
    )

    # Build App Store Connect API key using ENV variables
    api_key = app_store_connect_api_key(
      key_id: ENV["APPSTORE_KEY_ID"],
      issuer_id: ENV["APPSTORE_ISSUER_ID"],
      key_filepath: "./fastlane/Api_key.p8"
    )

    # Downloads code signing credentials using the API key
    match(
      type: "appstore",
      app_identifier: "org.hekmatullahamin.deployiosapp.DeployIosApp",
      readonly: true,
      api_key: api_key
    )

    # Retrieves the most recent TestFlight build number
    latest = latest_testflight_build_number(
      app_identifier: "org.hekmatullahamin.deployiosapp.DeployIosApp",
      api_key: api_key
    )

    # Increment build number locally
    increment_build_number(build_number: latest + 1)

    # Build app
    build_app(scheme: "iosApp")

    # Upload to TestFlight
    pilot(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end

