# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
      setup_ci(
        provider: "circleci"
      )
    match(type: "appstore",
     app_identifier: "org.hekmatullahamin.deployiosapp.DeployIosApp",
     readonly: true,
    api_key_path: "fastlane/api_key_info.json")

    latest = latest_testflight_build_number(
          version: "1.3",
          app_identifier: "org.hekmatullahamin.deployiosapp.DeployIosApp",
          api_key_path: "fastlane/api_key_info.json"
        )

        increment_build_number(build_number: latest + 1)
#     latest_testflight_build_number(version: "1.3")
#     increment_build_number({
#       build_number: latest_testflight_build_number + 1
#     })
#     increment_build_number(
#      build_number: 2
#     )
    build_app(scheme: "iosApp")
    pilot(api_key_path: "fastlane/api_key_info.json", skip_waiting_for_build_processing: true)
  end
end
