name: iOS TestFlight Release
on:
  workflow_dispatch:

jobs:
  deployIos:
    runs-on: macos-latest
    env:
      API_KEY_INFO: ${{ secrets.API_KEY_INFO }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.5
          bundler-cache: true
          working-directory: ios
      - name: Setup App Store Store Connect
        run: echo "$API_KEY_INFO" >> ./ios/fastlane/api_key_info.json
      - name: Build and Deploy to TestFlight
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        run: |
          cd ./ios
          bundle exec fastlane ios beta


#on:
#  push:
#    tags:
#      - '*-ios' # Trigger on tagging a commit with suffix "-ios" (e.g., 1.0.0-ios)