name: Deploy iOS to TestFlight via reusable workflow

on:
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: HekmatullahAmin/kmp-publish-ios-on-testflight-action/.github/workflows/ios-testflight-deploy.yml@master
    with:
      ruby-version: '3.3.5'
      working-directory: iosApp
      scheme: iosApp

    secrets:
#      API_KEY_INFO: ${{ secrets.API_KEY_INFO }}
      APPSTORE_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
      APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
      APPSTORE_PRIVATE_KEY: ${{ secrets.APPSTORE_PRIVATE_KEY }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
