name: Deploy iOS to TestFlight via Composite Action

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Deploy iOS Action
        uses: HekmatullahAmin/kmp-publish-ios-on-testflight-action@master
        with:
          ruby-version: '3.3.5'
          appstore-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          appstore-issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          appstore-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
          match-password: ${{ secrets.MATCH_PASSWORD }}
          match-git-basic-auth: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
